kind: pipeline
name: composer-validate
type: docker

steps:
  - name: validate
    image: php:7.4-cli
    pull: if-not-exists
    entrypoint: [ /bin/bash ]
    commands:
      - cd /drone/src/
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
      - php composer-setup.php
      - php -r "unlink('composer-setup.php');"
      - php composer.phar validate --no-check-all --no-check-publish
  - name: install
    image: php:7.4-cli
    pull: if-not-exists
    entrypoint: [ /bin/bash ]
    commands:
      - apt-get update && apt-get install git -yqq
      - cd /drone/src/
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
      - php composer-setup.php
      - php -r "unlink('composer-setup.php');"
      - COMPOSER_MEMORY_LIMIT=-1 php composer.phar install --prefer-dist

trigger:
  event:
    - push
