parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

    api_response.listener:
        class: Homeapp\ApiResponseBundle\Listener\ApiResponseListener
        arguments:
            - '@jms_serializer.serializer'
        tags:
            - { name: kernel.event_listener, event: kernel.view }