parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

    ApiResponseBundle\:
        resource: '../ApiResponseBundle/*'

    api_response.listener:
        alias: ApiResponseBundle\Listener\ApiResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.view }