parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

    api_response.listener:
        class: Homeapp\UtilsBundle\Listener\ApiResponseListener
        arguments:
            - '@jms_serializer.serializer'
        tags:
            - { name: kernel.event_listener, event: kernel.view }

    homeapp.guzzle.message_formatter:
        public: false
        class: Homeapp\UtilsBundle\Logger\NoBinaryFormatter
        arguments: ["{hostname} {req_header_User-Agent} - [{date_common_log}] \"{method} {target} HTTP/{version}\" {code} \n{response}\n--------\n{error}"]

    homeapp.guzzle.post_message_formatter:
        public: false
        class: Homeapp\UtilsBundle\Logger\NoBinaryFormatter
        arguments: ["{hostname} {req_header_User-Agent} - [{date_common_log}] \"{method} {target} HTTP/{version}\" {code} \n{req_body}\n--------\n{response}\n--------\n{error}"]
